### ISSUE TITLE
Security update

### ISSUE THREAD

**Issue by SillatL** [centre-for-educational-technology/tinda#1]

**Comment by pjotrsavitski** [comment]
[This branch](https://github.com/centre-for-educational-technology/tinda/tree/quick-and-dirty-d88) should be a **quick and dirty** first step in moving to Drupal version 8.8.

It needs to be checked and some modules (if not all) will have to be updated. It seemed that at least some of the versions that are currently being used are not compatible with Drupal version 8.8 and would need to be updated.

Running `composer outdated "drupal/*"` should display a list of all Drupal related modules and indicate current and latest version.

Drupal should be updated and configured according to [this guide](https://www.drupal.org/docs/updating-drupal/migrating-the-composer-project-for-drupal-earlier-than-880).

Please see **require** section of the `composer.json` file for list of all modules and currently required versions. Be ready to remove some of the patches defined in **extra.patches** subsection.

[This](https://www.drupal.org/node/3018145) should explain how the **sync** setting should be changed during migration.

**Comment by pjotrsavitski** [comment]
Modules, latest version and requirements:

* drupal/admin_toolbar - 2.4 - ^8.8.0 || ^9.0
* drupal/allowed_formats - 1.3 - no specific version required (does not yet work with version 9)
* drupal/anonymous_redirect - 2.2-beta3 - just version 8
* drupal/csv_importer - 1.11 - ^8 || ^9
* drupal/dropzonejs - 2.3 - ^8.8 || ^9 (ours is an alder beta or alpha; also check out bower-asset/dropzone as a newer version is available; locally applied patch is no longer needed for the latest version)
* drupal/email_registration - 1.1 - ^8.7.7 || ^9 (we seem to be using dev version)
* drupal/login_destination - 2.0-beta1 (we seems to be running 1.0-alpha)
* drupal/paragraphs - 1.12 - ^8.8 || ^9 (we are using an older version)
* drupal/taxonomy_access_fix - 3.1 - ^8.8 || ^9 (we are on the 2.x branch)
* drupal/views_fieldsets - 3.3 - 8.x (not available for version 9 and had no releases since 2018)
* drupal/views_infinite_scroll - 1.7- ^8.8 || ^9

Some modules will need to be updated as might not work well with version 8.8+. Ideally, all of those will need to be updated. If some of the modules are now abandoned, then a solution for updating to version 9 might be required.

**Comment by pankajchejara23** [comment]
Drupal updated to 8.9.11
