### ISSUE TITLE
Fix match interaction submission error

### ISSUE THREAD

**Issue by SillatL** [centre-for-educational-technology/tinda#5]
![Screenshot 2020-10-21 at 10 54 37](https://user-images.githubusercontent.com/29249989/96709357-426d7a00-13a3-11eb-849c-805c4f375874.png)

**Comment by SillatL** [comment]
Questionnaire answer submission is not working so data is not collected. 
We need to students data saved.

**Comment by pjotrsavitski** [comment]
I have no idea what is the logic of the data that is being submitted, but the code with notice is here:
https://github.com/centre-for-educational-technology/tinda/blob/master/www/web/modules/custom/qualification_test_rounds/src/Builder/MatchBuilder.php#L270

If each pair should have two elements, then indexes should be zero and one, not one and two. If that is something else, then [isset()](https://www.php.net/manual/en/function.isset.php) could be used to handle the situation of items at index not being present. Example: `if (isset($pair[1]) && isset($pair[2]) && $pair[1] && $pair[2])`

It seems to be a validation method that is not itself dealing with storage of data. I haven't got a clue what it should be doing, but notices are there because there is no element at position **2**.

**Comment by pankajchejara23** [comment]
As Pjotr said the issue was related to validation part that is now resolved.
